# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'currency.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(922, 544)
        Dialog.setMouseTracking(True)
        Dialog.setTabletTracking(True)
        Dialog.setFocusPolicy(QtCore.Qt.ClickFocus)
        Dialog.setAcceptDrops(False)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Cryptocurrency = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Cryptocurrency.setFont(font)
        self.Cryptocurrency.setObjectName("Cryptocurrency")
        self.horizontalLayout.addWidget(self.Cryptocurrency)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.etherium = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.etherium.setFont(font)
        self.etherium.setStyleSheet("color: rgb(207, 207, 207);")
        self.etherium.setObjectName("etherium")
        self.verticalLayout_5.addWidget(self.etherium)
        self.bitcoin = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bitcoin.setFont(font)
        self.bitcoin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.bitcoin.setStyleSheet("color: rgb(207, 207, 207);\n"
"border-color: rgb(207, 207, 207);")
        self.bitcoin.setTristate(True)
        self.bitcoin.setObjectName("bitcoin")
        self.verticalLayout_5.addWidget(self.bitcoin)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("OIP.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_9.addWidget(self.buttonBox)
        self.Cryptocurrency.setBuddy(self.Cryptocurrency)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Crypto Currency "))
        self.Cryptocurrency.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:400; color:#cfcfcf;\">Choose your Currency </span></p></body></html>"))
        self.etherium.setText(_translate("Dialog", "Euro "))
        self.bitcoin.setText(_translate("Dialog", "Dollar "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
